E_commerce/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.conf import settings
from django.conf.urls.static import static
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView

urlpatterns = [
    path('', include('produto.urls')),
    path('perfil/', include('perfil.urls')),
    path('pedido/', include('pedido.urls')),
    path('admin/', admin.site.urls),

    # API
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/swagger/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path('api/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pedido/urls.py
from django.urls import path
from . import views

app_name = 'pedido' #pedido:{name}

urlpatterns = [
    path('', views.Pagar.as_view(), name='pagar'),
    path('salvarpedido/', views.SalvarPedido.as_view(), name='salvarpedodo/'),
    path('detalhes/<int:pk>', views.Detalhes.as_view(), name='detalhes'),
]

produto/urls.py
from django.urls import path
from . import views

app_name = 'produto' #produto:{name}

urlpatterns = [
    path('', views.ListaProdutos.as_view(), name='lista'),
    path('<slug>', views.DatalheProdutos.as_view(), name='detalhe'),
    path('addaocarrinho/', views.AddAoCarrinho.as_view(), name='addaocarrinho'),
    path('removerdocarrinho/', views.RemoverDoCarrinho.as_view(), name='removerdocarrinho'),
    path('carrinho/', views.Carrinho.as_view(), name='carrinho'),
    path('resumodacompra/', views.ResumoDaCompra.as_view(), name='resumodacompra'),

]

produto/models.py
from django.db import models
import os 
from PIL import Image 
from django.db import models
from E_commerce import settings
from django.utils.text import slugify
from utils import utils
from django.contrib.auth.models import User 

# Create your models here.
class Produto(models.Model):
    nome = models.CharField(max_length=255)
    descricao_curta = models.CharField(max_length=255)
    descricao_longa = models.TextField()
    imagem = models.ImageField(upload_to='produto_imagens/%y/%m/', blank=True, null=True)
    slug = models.SlugField(unique=True, blank=True, null=True)
    preco_marketing = models.FloatField(verbose_name='Preço')
    preco_marketing_promo = models.FloatField(default=0, verbose_name='Preço Promo')
    tipo = models.CharField(
        default='V',
        max_length=1,
        choices=(
            ('V', 'Variavel'),
            ('S', 'Simples'),
        )
    )

    def get_preco_formatado(self):
        return utils.formata_preco(self.preco_marketing)
    get_preco_formatado.short_description = 'Preço'

    def get_preco_promo_formatado(self):
        return utils.formata_preco(self.preco_marketing_promo)
    get_preco_promo_formatado.short_description = 'Preço Promo'

    #Redefine tamnho da imagem
    @staticmethod
    def resize_image(img, new_width=800):
        img_full_path = os.path.join(settings.MEDIA_ROOT, img.name)
        img_pil = Image.open(img_full_path)
        original_width, original_height = img_pil.size

        if original_width <= new_width:
            img_pil.close()
            return
        
        new_height = round((new_width * original_height) / original_width)

        new_img = img_pil.resize((new_width, new_height), Image.LANCZOS)
        new_img.save(
            img_full_path,
            optimize=True,
            quality=50,
        )

    def save(self, *args, **kwergs):

        if not self.slug:
            slug= f'{slugify(self.nome)}'
            self.slug = slug

        super().save(*args, **kwergs)

        max_image_size = 800

        if self.imagem:
            self.resize_image(self.imagem, max_image_size)

    def __str__(self):
        return self.nome
    

class Variacao(models.Model):
    produto = models.ForeignKey(Produto, on_delete=models.CASCADE)
    nome = models.CharField(max_length=50, blank=True)
    preco = models.FloatField()
    preco_promo = models.FloatField(default=0)
    estoque = models.PositiveSmallIntegerField(default=1)

    def __str__(self):
        return self.nome or self.produto.nome
    
    class Meta:
        verbose_name = 'Variação'
        verbose_name_plural = 'Variações'

class AvaliacaoProduto(models.Model):
    produto = models.ForeignKey(Produto, on_delete=models.CASCADE)
    # user = models.OneToOneField(User, on_delete=models.CASCADE)
    nota = models.FloatField()
    comentario =models.CharField( max_length=255)

    def __str__(self):
        return self. nome or self.produto.nome
        
    class Meta:
        verbose_name = 'Avaliação'
        verbose_name_plural = 'Avaliações'

produto/views.py
from django.shortcuts import redirect, get_object_or_404, render
from django.urls import reverse
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views import View
from django.http import HttpResponse
from django.contrib import messages
from . import models
from pprint import pprint


class ListaProdutos(ListView):
    model = models.Produto
    template_name = 'produto/lista.html'
    context_object_name = 'produtos'
    paginate_by = 3

class DatalheProdutos(DetailView):
    model = models.Produto
    template_name = 'produto/detalhe.html'
    context_object_name = 'produto'
    slug_url_kwarg = 'slug'

class DatalhesProdutos(View):
    pass

class AddAoCarrinho(View):
    def get(self, *args, **kwargs):

        # if self.request.session.get('carrinho'):
        #     del self.request.session['carrinho']
        #     self.request.session.save()

        #http_referer está guadandoa aba anterior
        http_referer = self.request.META.get(
            'HTTP_REFERER',
            reverse('produto:lista')
        )

        #variacao_id está guardando o "vid" da url, que vai funcionar como um id 
        variacao_id = self.request.GET.get('vid')

        #caso não tenha um vid(ele esteja vasio ou não exista), retorna a aba anterior e mostra uma mensagem
        if not variacao_id:
            messages.error(
                self.request,
                'Produto não existe'
            )
            return redirect(http_referer)
        
        #recebe a variação apartir da variacao_id(o vid que ta sendo passado)
        #caso variacao_id não exista retorna erro 404
        variacao = get_object_or_404(models.Variacao, id=variacao_id)

        #criando as variaveis que vão ser passadas pra o carrinho
        produto = variacao.produto
        produto_nome = produto.nome
        produto_id = produto.id
        variacao_nome = variacao.nome or ''
        variacao_estoque = variacao.estoque
        preco_unitario = variacao.preco
        preco_unitario_promo = variacao.preco_promo
        quantidade = 1 
        slug = produto.slug
        imagem = produto.imagem

        #caso não tenha imagem passa espaço vazio
        if imagem:
            imagem = imagem.name
        else:
            imagem = ''

        #varifica se há produtop em estoque 
        if variacao.estoque < 1:
            messages.error(
                self.request,
                'Estoque insuficiente'
            )
            return redirect(http_referer)

        #se não tem um carrinho, então vai criar um carrinho 
        if not self.request.session.get('carrinho'):
            self.request.session['carrinho'] = {}
            self.request.session.save()

        #salva o carrinho nessa variavel carrinho
        carrinho = self.request.session['carrinho']

        #caso o id da varição esteja dentro do carrinho
        if variacao_id in carrinho:
            quantidade_carrinho = carrinho[variacao_id]['quantidade']
            quantidade_carrinho += 1

            #verifica se no estoque tem a quantidade que deve ser add ao carrinho
            #caso não tenha mostra mensagem de aviso e adiciona a quantidade que for possivel
            if variacao_estoque < quantidade_carrinho:
                messages.warning(
                    self.request,
                    f'Estoque insuficiente para {quantidade_carrinho}x do produto: "{produto_nome}"'
                    f'Adcionamos {variacao_estoque}'
                )
                quantidade_carrinho = variacao_estoque

            #passa para o carrinho a quantide e o preço total(preço * quantidade)
            carrinho[variacao_id]['quantidade'] = quantidade_carrinho
            carrinho[variacao_id]['preco_quantitativo'] = preco_unitario * quantidade_carrinho
            carrinho[variacao_id]['preco_quantitativo_promo'] = preco_unitario_promo * quantidade_carrinho

        else:
            #passando os dados do produto pra dentro do carrinho
            carrinho[variacao_id] = {
                'produto_nome': produto_nome,
                'produto_id': produto_id, 
                'variacao_nome': variacao_nome,
                'variacao_id': variacao_id,
                'preco_unitario': preco_unitario,
                'preco_unitario_promo': preco_unitario_promo,
                'preco_quantitativo': preco_unitario,
                'preco_quantitativo_promo': preco_unitario_promo,
                'quantidade': 1,
                'slug': slug,
                'imagem': imagem,
            }

        #salva
        self.request.session.save()

        #Mensagem de confirmação de adição ao carrinho
        messages.success(
            self.request,
            f'Produto {produto_nome} {variacao_nome} adicionado ao seu carrinho'
        )

        print(carrinho)
        #retorna a aba antirior, no caso para o detelhs do produto
        return redirect(http_referer)

class RemoverDoCarrinho(View):
    def get(self, *args, **kwargs):

        #http_referer está guadandoa aba anterior
        http_referer = self.request.META.get(
            'HTTP_REFERER',
            reverse('produto:lista')
        )

        #variacao_id está guardando o "vid" da url, que vai funcionar como um id 
        variacao_id = self.request.GET.get('vid')

        #se a variação não existe retorna para a pagina anterior 
        if not variacao_id:
            return redirect(http_referer)
        
        #se o carrinho não existe retorna para a pagina anterior 
        if not self.request.session.get('carrinho'):
            return redirect(http_referer)
        
        #se o id da varição não exite no carrihno retorna para a pagina anterior
        if variacao_id not in self.request.session['carrinho']:
            return redirect(http_referer)
        
        #guarda o carrinho em uma variavel carrinho
        carrinho = self.request.session['carrinho'][variacao_id]

        #mensssagem de sucesso 
        messages.success(
            self.request, 
            f'Produto {carrinho["produto_nome"]} {carrinho["variacao_nome"]} foi removido do carrinho'
        )

        #deleta e salva 
        del self.request.session['carrinho'][variacao_id]
        self.request.session.save()

        return redirect(http_referer)

class Carrinho(View):
    def get(self, *args, **kwargs):
        contexto = {
            'carrinho': self.request.session.get('carrinho', {})
        }
        return render(self.request, 'produto/carrinho.html', contexto)

class ResumoDaCompra(View):
    pass

produto/templates/produto/carrinho.html
{% extends 'base.html' %}
{% load omfilters %}
{% load static %}

{% block conteudo %}

{% if request.session.carrinho %}
<div class="row mt-3">
    <div class="col">
        <h3>Carrinho de compras</h3>
        <p class="lead">Os produtos, quantidades e preços que você escolheu.</p>

        <div class="table-responsive">
            <table class="table">
                <tr>
                    <th class="d-none d-lg-block">Imagem</th>
                    <th>Produto</th>
                    <th>V.</th>
                    <th>QTD.</th>
                    <th>Total</th>
                </tr>

                {% for linha in carrinho.values %}
                <tr>
                    <td class="d-none d-lg-block">
                        <img class="cart-img" src="{% get_media_prefix%}{{ linha.imagem}}">
                    </td>
                    <td>
                  
                        <a href="{% url 'produto:detalhe' linha.slug %}">
                        {{ linha.produto_nome }}
                        </a>

                        <a class="ml-3" href="{% url 'produto:removerdocarrinho' %}?vid={{ linha.variacao_id }}">
                            <i class="fas fa-times-circle text-danger" aria-hidden="true"></i>
                        </a>
                    </td>
                    <td>{{ linha.variacao_nome}}</td>
                    <td> {{ linha.quantidade}} </td>

                    {% if linha.preco_quantitativo_promo %}
                    <td> {{ linha.preco_quantitativo_promo | formata_preco}} </td>
                    {% else %}
                    <td> {{ linha.preco_quantitativo | formata_preco}} </td>
                    {% endif %}
                </tr>
                {% endfor %}

            </table>
        </div>
    </div>
</div>



<div class="row mt-3">
    <div class="col-lg">
        <p class='lead'>Total no carrinho</p>

        <div class='table-responsive'>
            <table class="table">
                <tr>
                    <td class="font-weight-bold">Total</td>
                    <td> {{ carrinho | cart_totals | formata_preco}} </td>
                </tr>
            </table>
        </div>
    </div>
    <div class="col-lg mt-auto">
        <a class="btn btn-lg btn-block btn-primary" href="#">
            Finalizar a compra
        </a>
    </div>
</div>

{% else %}
<div class="row mt-3">
    <div class="col">
        <h3>Carrinho vazio</h3>
        <p class="lead">Não há produtos no seu carrinho</p>
    </div>
</div>

{% endif %}
{% endblock conteudo %}

produto/templates/produto/detalhe.html
{% extends 'base.html' %}
{% load omfilters %}

{% block conteudo %}
<div class="row">
    <div class="col-lg">
        <div class="row no-gutters">
            <div class="col-lg-12">

                {% if produto.imagem %}
                    <img class="img-fluid" src="{{ produto.imagem.url }}">
                {% endif %}

            </div>
        </div>
    </div>
    <div class="col-lg">
        <div class="mt-4 mt-lg-0">

            <h1 class="h2">{{ produto.nome }}</h1>

            <p class="lead">{{ produto.descricao_curta }}</p>

            <p class="lead">

                {% if produto.preco_marketing_promo %}
                    <span id="variation-preco-promocional" class="lead product-price">{{ produto.preco_marketing_promo | formata_preco }}</span>
                    <span id="variation-preco"
                        class="lead product-old-price text-muted">{{ produto.preco_marketing | formata_preco }}</span>

                {% else %}
                    <span id="variation-preco" class="lead product-price">{{ produto.preco_marketing | formata_preco }}</span>

                {% endif %}

            </p>

            <form action="{% url 'produto:addaocarrinho' %}" id="form-add-to-cart">
                <div class="form-group">
                    <select id="select-variacoes" name="vid" class="form-control form-control-lg">

                        {% for variacao in produto.variacao_set.all %}

                            {% if variacao.preco_promo%}
                                <option data-preco="{{ variacao.preco| formata_preco }}" data-preco-promocional=" {{ variacao.preco_promo | formata_preco }}" value="{{ variacao.id }}">

                                    {% if variacao.nome %}
                                        {{ variacao.nome }}

                                    {% else %}
                                        {{ variacao }}
                                    {% endif %}

                                </option>

                            {% else %}
                            <option data-preco="{{ variacao.preco | formata_preco }}" value="{{ variacao.id }}">

                                {% if variacao.nome %}
                                    {{ variacao.nome }}

                                {% else %}
                                    {{ variacao }}

                                {% endif %}

                            </option>
                            {% endif %}

                        {% endfor %}

                    </select>
                </div>

                <div class="text-left">
                    <button type="submit" class="btn btn-primary btn-lg btn-block">
                        <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                        Adicionar ao carrinho
                    </button>
                </div>

            </form>


        </div>
    </div>
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="mt-5 mb-5">
            <h2 class="text-center">{{ produto.nome }}</h2>
            {{ produto.descricao_longa | linebreaks }}
        </div>
    </div>
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="mt-5 mb-5">
            <h2 > nota </h2>
            <textarea  rows="6" cols="150">
                
            </textarea>
        </div>
    </div>
</div>

{% endblock conteudo %}

produto/templates/produto/lista.html
{% extends 'base.html' %}
{% load omfilters %}

{% block conteudo %}
<div class="row">
    <div class="col-lg-12">
        <div class="card-columns">

            {% for produto in produtos %}
            <div class="card">

                {% if produto.imagem %}
                <a href="{{ produto.slug }}">
                    <img class="card-img-top" src="{{ produto.imagem.url }}" alt="{{ produto.nome }}">
                </a>
                {% endif %}

                <div class="card-body">
                    <h5 class="card-title">{{ produto.nome }}</h5>
                    <p class="card-text"> {{ produto.descricao_curta }} </p>
                    <div class="container product-price-block text-center">

                        {% if produto.preco_marketing_promo %}
                        <span class="product-price">
                           {{ produto.preco_marketing_promo | formata_preco }}
                        </span>
                        <span class="product-old-price text-muted">
                            {{ produto.preco_marketing | formata_preco}}
                        </span>

                        {% else %}
                        <span class="product-price">
                            {{ produto.preco_marketing | formata_preco }}
                         </span>

                        {% endif %}
                    </div>
                </div>
                <div class="card-footer bg-transparent border-top-light-custom text-center">
                    <a href="{% url 'produto:detalhe' produto.slug %}" class="btn btn-primary btn-sm m-1 btn-block">
                        <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                        Comprar
                    </a>
                </div>
            </div>
            {% endfor %}

        </div>
    </div>
</div>

<div class="row mt -4">
    <div class="col">
        {% include 'parciais/_pagination.html' %}
{% endblock conteudo %}